#!/usr/bin/env python3
"""
Rewrite an email draft in Rushabh's voice using the brand guidelines.
Uses the same voice rules as Delphi/send_india_followup + email_rushabh_voice_brand.txt.

Usage:
  poetry run python scripts/rewrite_email_rushabh_voice.py [path_to_draft.md]
  Default: data/imports/24_WebSite_Leads/email_vladimir_kilunin_FINAL.md
"""

from __future__ import annotations

import asyncio
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

try:
    from dotenv import load_dotenv
    load_dotenv(PROJECT_ROOT / ".env")
except Exception:
    pass


def _extract_subject_and_body(content: str) -> tuple[str, str]:
    """Extract Subject: line and body from FINAL email markdown."""
    subject = ""
    for line in content.splitlines():
        if line.strip().startswith("Subject:"):
            subject = line.replace("Subject:", "").strip()
            break
    # Body: from "Dear Vladimir" or "Hi Vladimir" through "Director — Machinecraft"
    start = content.find("Dear Vladimir,")
    if start < 0:
        start = content.find("Hi Vladimir,")
    if start < 0:
        start = 0
    rest = content[start:]
    end = rest.find("Director — Machinecraft")
    if end >= 0:
        rest = rest[: end + len("Director — Machinecraft")]
    body = rest.strip()
    return subject or "Follow-up: PF1 for Komplektant", body


async def rewrite_in_rushabh_voice(draft_path: Path) -> str:
    from ira.prompt_loader import load_prompt
    from ira.services.llm_client import get_llm_client

    raw = draft_path.read_text(encoding="utf-8")
    subject, body = _extract_subject_and_body(raw)

    voice_brand = load_prompt("email_rushabh_voice_brand")

    system = f"""You ARE Rushabh Doshi. You're the Director at Machinecraft (thermoforming machines). You're rewriting an existing email draft so it sounds like you — conversational, warm, direct. Keep ALL factual content: machine model (PF1-X-2012), price (250,000 USD), lead time, spec table, reference table, references (Jaguar, Mirsant, Middle East 10 machines, India clients, Dutch Tides), process questions, Formpack cross-sell, and the CTA (video call Thu/Fri).

RUSHABH'S VOICE RULES:
- Open with "Hi Vladimir," (or keep "Dear Vladimir," if the draft is formal re-engagement).
- Use "I" not "we" — e.g. "I wanted to share…" not "We recommend…"
- Short paragraphs. Keep the spec table and reference table as-is (they're needed).
- No corporate buzzwords. Conversational but professional.
- Single clear CTA at the end. Sign-off: "Best regards," then "Rushabh Doshi", "Director — Machinecraft"
- Do not remove or change any numbers, machine models, or client names.

--- BRAND GUIDELINES ---
{voice_brand}
--- END ---

Output format: first line "Subject: <subject>", then a blank line, then the full email body. Do not add markdown headers or extra commentary."""

    user = f"""Rewrite this email in Rushabh's voice. Keep every fact, table, and number. Only change tone and phrasing to sound like Rushabh.

CURRENT SUBJECT: {subject}

CURRENT BODY:
{body}

Output the new email (Subject: then body):"""

    client = get_llm_client()
    out = await client.generate_text(
        system=system,
        user=user[:28000],
        max_tokens=3500,
        temperature=0.35,
        name="rewrite_email_rushabh_voice",
    )
    return out.strip()


def main() -> None:
    draft_path = PROJECT_ROOT / "data/imports/24_WebSite_Leads/email_vladimir_kilunin_FINAL.md"
    if len(sys.argv) > 1:
        draft_path = Path(sys.argv[1])
    if not draft_path.exists():
        print(f"File not found: {draft_path}")
        sys.exit(1)

    result = asyncio.run(rewrite_in_rushabh_voice(draft_path))

    out_path = draft_path.parent / (draft_path.stem + "_RUSHABH_VOICE.md")
    header = "# Same email — Rushabh's voice\n\n"
    header += "Generated by rewrite_email_rushabh_voice.py using email_rushabh_voice_brand.txt.\n\n---\n\n"
    out_path.write_text(header + result, encoding="utf-8")
    print("--- RUSHABH VOICE VERSION ---\n")
    print(result)
    print("\n---")
    print(f"Written to: {out_path}")


if __name__ == "__main__":
    main()
